services:
  db:
    container_name: mongo-db-container
    image: mongo:4.0
    ports:
      - '27017:27017'
  server:
    build: ./server
    container_name: node-server-container
    depends_on:
      - db
    ports:
      - '4000:4000'
    restart: always
  client:
    container_name: react-client-container
    build: ./client
    depends_on:
      - server
    ports:
      - '3000:3000'
    restart: always
version: '3.7'
